"""Deterministic mathematical geometry primitives for WZHK visual runtimes."""

from .audio_mapping import (
    AudioInputs,
    AudioMappingConfig,
    MappedAudioResponse,
    map_audio,
    propagation_wave,
)
from .choreography import (
    ChoreographySection,
    GeometryChoreography,
    GeometryTransition,
    ResolvedGeometryState,
    bars_to_seconds,
    beats_to_seconds,
    musical_time_to_seconds,
    resolve_choreography,
    scattered_sections,
    seconds_per_bar,
    seconds_per_beat,
)
from .contracts import (
    EasingId,
    GenerativeModel,
    GeometryPreviewMode,
    GeometryPreviewOverride,
    GeometryPreviewRequest,
    GeometrySectionId,
    IndexedDomainSpec,
    MusicalTime,
    MusicalTimeUnit,
    PreviewAudioMode,
    ShapeId,
    ShapeSpec,
)
from .shapes import (
    TRUSTED_SHAPE_IDS,
    Point3,
    UVPoint,
    easing_progress,
    indexed_uv_domain,
    morph_points,
    morph_shapes,
    sample_shape,
)

__all__ = [
    "AudioInputs",
    "AudioMappingConfig",
    "ChoreographySection",
    "EasingId",
    "GenerativeModel",
    "GeometryChoreography",
    "GeometryPreviewMode",
    "GeometryPreviewOverride",
    "GeometryPreviewRequest",
    "GeometrySectionId",
    "GeometryTransition",
    "IndexedDomainSpec",
    "MappedAudioResponse",
    "MusicalTime",
    "MusicalTimeUnit",
    "Point3",
    "PreviewAudioMode",
    "ResolvedGeometryState",
    "ShapeId",
    "ShapeSpec",
    "TRUSTED_SHAPE_IDS",
    "UVPoint",
    "bars_to_seconds",
    "beats_to_seconds",
    "easing_progress",
    "indexed_uv_domain",
    "map_audio",
    "morph_points",
    "morph_shapes",
    "musical_time_to_seconds",
    "propagation_wave",
    "resolve_choreography",
    "sample_shape",
    "scattered_sections",
    "seconds_per_bar",
    "seconds_per_beat",
]
